# Generated by Django 4.2.13 on 2024-06-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_history', '0003_patient_address_patient_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('admin', 'Can access everything in the program'), ('doctor', 'Can acess everything in the programe'), ('secretary', 'Can only see information, but not alter it')]},
        ),
    ]
