# Generated by Django 4.2.13 on 2024-06-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_history', '0004_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
    ]
