# Generated by Django 4.2.13 on 2024-06-01 03:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identification_card', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reason_visit', models.TextField()),
                ('records', models.TextField()),
                ('current_diseases', models.TextField()),
                ('physical_exam', models.TextField()),
                ('diagnostic', models.TextField()),
                ('therapeutic_plan', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='m_history.patient')),
            ],
        ),
    ]
